name: Generate Stats Images
on:
  push:
    branches: [master]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt
      - name: Generate images
        run: |
          python3 --version
          python3 generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          EXCLUDE_FORKED_REPOS: false
      - name: Commit to the repo
        run: |
          git config --global user.name "ErrorGamer2000/stat-bot"
          git config --global user.email "github-stats[bot]@errorgamer2000.github.io"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update stats' || echo
          git push
